using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ExpenseTracker.Models;

namespace ExpenseTracker.Helpers
{
    public class ExpenseReportPdf : IDocument
    {
        private readonly ReportViewModel _model;

        public ExpenseReportPdf(ReportViewModel model)
        {
            _model = model;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Text($"Expense Report - {_model.SelectedMonth}")
                    .FontSize(20).Bold().FontColor(Colors.Blue.Medium);

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    // Total Expenses
                    col.Item().Text($"Total Expenses: RM {_model.TotalExpenses:F2}")
                        .FontSize(14).Bold();

                    // Budget Summary (if available)
                    if (_model.BudgetLimit.HasValue)
                    {
                        col.Item().Text($"Budget Limit: RM {_model.BudgetLimit.Value:F2}")
                            .FontColor(Colors.Grey.Darken1);

                        col.Item().Text($"Remaining Budget: RM {_model.RemainingBudget:F2}")
                            .FontColor(_model.IsOverBudget ? Colors.Red.Medium : Colors.Green.Darken2)
                            .Bold();

                        if (_model.IsOverBudget)
                        {
                            col.Item().PaddingTop(5).Text("⚠ ALERT: Monthly spending exceeded the budget limit!")
                                .FontColor(Colors.Red.Medium).FontSize(12).Bold();
                        }
                    }

                    // Divider
                    col.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    // Table
                    if (_model.CategorySummaries.Any())
                    {
                        col.Item().PaddingBottom(5).Text(text => text.Span("Breakdown by Category:").Bold());

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn();
                                columns.ConstantColumn(100);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Category").Bold();
                                header.Cell().Text("Amount (RM)").AlignRight().Bold();
                            });

                            foreach (var cat in _model.CategorySummaries)
                            {
                                table.Cell().Text(cat.Category);
                                table.Cell().Text(cat.TotalAmount.ToString("F2")).AlignRight();
                            }
                        });
                    }
                    else
                    {
                        col.Item().Text("No expense data available for this period.");
                    }

                    // (Optional) Pie Chart Image Placeholder
                    // You can use a pie chart screenshot (converted to base64) and embed it:
                    // col.Item().Image(Base64ImageHelper.LoadChart("chart.png")).FitWidth();
                });

                page.Footer().AlignCenter().Text(txt =>
                {
                    txt.Span("Generated by FRIENDS Expense Tracker - ");
                    txt.Span(DateTime.Now.ToString("f")).Italic().FontSize(10);
                });
            });
        }
    }
}


